### ISSUE TITLE
add README.md in pipline folder

### ISSUE THREAD

**Issue by KonradHoeffner** [Ayuei/DeBEIR#13]
Please add a README.md into the examples/pipeline folder to specific the setup steps. With no setup, it aborts with the following error message:

RuntimeError: Elasticsearch instance cannot be reached at <AsyncElasticsearch(['http://localhost:9200'])>

**Comment by Ayuei** [comment]
I added a ```README.md``` in this commit [99e3e07](https://github.com/Ayuei/DeBEIR/commit/99e3e0762e3ef583aa19d69aecc8f9d7016a72bb)

Which hopefully makes it clearer
