### ISSUE TITLE
quick example possible?

### ISSUE THREAD

**Issue by KonradHoeffner** [Ayuei/DeBEIR#14]
Even on an i9-12900k without a GPU the fastest example estimates 4 hours of duration. Is it possible to create an example that can be run faster or to modify one of the existing ones?

**Comment by Ayuei** [comment]
I think I can potentially package an index prebuilt for download. Also, which example are you referring to?

**Comment by KonradHoeffner** [comment]
I think it was both [finetune_biencoder](https://github.com/Ayuei/DeBEIR/tree/main/examples/finetune_biencoder) and [hparam_tuning](https://github.com/Ayuei/DeBEIR/tree/main/examples/hparam_tuning) that estimated around 4 hours or slightly more of runtime.

**Comment by Ayuei** [comment]
I added a limit flag for the two examples you mentioned https://github.com/Ayuei/DeBEIR/commit/08e8e3b927149acbd6230b4cba206867e520380d

Run the examples again but with ```--limit 100``` or any number less than the total number of samples.

As for the integrated intel CPUs/GPUs, I added a commit to allowing hooking into the fit/training loop. So you could do something like this:

```python3
    # Snippet from biencoder finetuning

   import intel_extension_for_pytorch as ipex
   
   def ipex_hook(self, **kwargs):
        param_optimizer = list(loss_model.named_parameters())

       no_decay = ['bias', 'LayerNorm.bias', 'LayerNorm.weight']
       optimizer_grouped_parameters = [
                {'params': [p for n, p in param_optimizer if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},
                {'params': [p for n, p in param_optimizer if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
        ]

        optimizer = optimizer_class()

        optimizer = kwargs['optimizer_class'](optimizer_grouped_parameters, lr = 2e-5) 
        model, optimizer = ipex.optimize(self.model, optimizer=optimizer)
         self.model = model

        # Wrapper needed as Sentence Transformer backend library will attempt to create it's own optimizer
        def optimizer_wrapper(*args, **kwargs):
              return optimizer

    trainer = SentenceTransformerTrainer(
        # Reuse the dataset with lazy static, so we don't have to do the preprocessing repeatedly
        dataset=load_dataset(limit),
        hparams_config=HparamConfig.from_json("hparam_cfg.json"),
        evaluator_fn=evaluation.BinaryClassificationEvaluator,
    )
   
    # Overload with our prehook
    trainer.prehook = ipex_hook

    trainer.fit()

```
