### ISSUE TITLE
upgrade torch major version to 2

### ISSUE THREAD

**Issue by KonradHoeffner** [Ayuei/DeBEIR#15]
According to requirements.txt, the outdated torch major version 1 is used while the current major version is 2.
Is it possible to upgrade to the current version?

**Comment by Ayuei** [comment]
I'll look into this. If it's backwards compatible it definitely should be, and if it is, I may spend some extra time to take advantage of the opaque types in this library as well.

**Comment by Ayuei** [comment]
All the tests seem to be passing and there wasn't much of an issue. I've updated the repository to set the torch version to be at least version 2.0 as well as updating other versions of other packages as well. https://github.com/Ayuei/DeBEIR/commit/5d536808e71536590d218d7c5813288eab5efc69
