### ISSUE TITLE
virtualenv vs venv in  installation instructions

### ISSUE THREAD

**Issue by KonradHoeffner** [Ayuei/DeBEIR#5]
```
$ python3 -m virtualenv venv
/usr/bin/python3: No module named virtualenv
```
Either add `pip install virtualenv` to the docs or use `-m venv` instead if that is enough, as it is shipped by default with Python3.3+, see <https://stackoverflow.com/questions/41573587/what-is-the-difference-between-venv-pyvenv-pyenv-virtualenv-virtualenvwrappe>.

Part of the JOSS review <https://github.com/openjournals/joss-reviews/issues/5017>.

**Comment by Ayuei** [comment]
Hi, thanks for the issue. Looking at the differences, virtualenv isn't required over venv. 

Fixed via 0248b43ffe58c0225ad3c644b0d4b34c584be37f
