### ISSUE TITLE
please add DeBEIR to PyPI

### ISSUE THREAD

**Issue by KonradHoeffner** [Ayuei/DeBEIR#7]
The documentation instructs to install from source, but ideally it should be installable from PyPI.

Part of the JOSS review <https://github.com/openjournals/joss-reviews/issues/5017>

**Comment by Ayuei** [comment]
Unfortunately this is not possible at the moment as there are direct (git) dependencies in the requirements, which is currently not allowed by PyPi. The solution would be first upload the direct dependencies to PyPi and reference them in DeBEIR.

However, these direct dependencies are other packages I am working on which I don't think are ready yet to be publicly uploaded to PyPi.

As a compromise, I'll be adding releases of the built wheel to this repository.
