### ISSUE TITLE
HTML documentation starting page about NIR, not DeBEIR

### ISSUE THREAD

**Issue by KonradHoeffner** [Ayuei/DeBEIR#8]
docs/debeir.html:

>  debeir
> 
> The NIR (Neural Index Ranker) source code library.
> 
> See ./main.py in the parent directory for an out-of-the-box runnable code.
> 
> Otherwise, check out notebooks in the parent directory for training your own model amongst other things.
> 

Part of the JOSS review <https://github.com/openjournals/joss-reviews/issues/5017>.

**Comment by Ayuei** [comment]
Fixed via [b75619f](https://github.com/Ayuei/DeBEIR/commit/b75619f8bcaece6420c7000dfab966b05ae59c7d)
